name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NETWORK: ${{ secrets.NETWORK }}
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd hardhat
          npm install
          npm install --save-dev hardhat@2.22.3
          npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Makefile
        run: make all
